# Generated by Django 2.2.1 on 2019-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('pseudo', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('nl', models.BooleanField()),
                ('statut', models.CharField(max_length=5)),
            ],
        ),
    ]
