# Generated by Django 2.2.6 on 2019-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaisite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ident',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
