# Generated by Django 2.2.6 on 2019-12-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaisite', '0002_auto_20191113_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ident',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
